describe('TEST 6', function() {
    it('TEST6.1', function() {
    cy.visit('https://admin.pkh.dojobox.id/')
    cy.get('#input-email').type('e@dojobox.id')
    cy.get('#input-password').type('admin')
    cy.get('#btn-login').click()
    cy.get('.mr-2 > b').should('have.text','Super Admin')
    cy.get('.d-flex > .btn').click() 

    cy.get('#user_fullname').type('Facilitator KUCING 1')
    cy.get('#user_email').type('kucing28@mail.com')                 ///////////////////////////----------
    cy.get('#user_is_active').select('Nonaktif')
    cy.get('#user_password').type('test123')
    cy.get('#user_province_id').select('ACEH')
    cy.get('#user_city_id').select('KAB. ACEH SELATAN')
    cy.get('#user_subdistrict_id').select('Bakongan')
    cy.get('#user_address').type('Jl. Jend. Sudirman No.Kav. 21, RT.10/RW.1, Kuningan, Karet, Kecamatan Setiabudi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12920')
    cy.get('.custom-control').click()
    cy.get('input[type="file"]').attachFile('kucing.jpg').should('exist')
    cy.get('#user_area_province_id').should('contain','ACEH').should('exist')
    cy.get('#user_area_city_id').should('contain','KAB. ACEH SELATAN').should('exist')
    cy.get('#user_area_subdistrict_id').should('contain','Bakongan').should('exist')

    cy.get('#add').click()
    cy.get('#modal-title').should('have.text','Success')
    cy.get('#modal-body').should('have.text','Penambahan fasilitator berhasil diproses')
    cy.wait(2000)
    cy.get('#generalModal > .modal-dialog > .modal-content > .modal-footer > .btn').click()
    cy.get('#add').click()
    cy.get('#modal-title').should('have.text','Error !')
    cy.get('#modal-body').should('have.text','Email sudah digunakan')
    cy.wait(2000)
    cy.get('#generalModal > .modal-dialog > .modal-content > .modal-footer > .btn').click()

    cy.get('#accordionSidebar > :nth-child(1) > .nav-link').click()
    cy.wait(2000)
    cy.get('#dataTable_filter > label > .form-control').type('kucing15@mail.com') ////////////----------
    cy.wait(2000)
    cy.get('.odd > :nth-child(3)').should('have.text','kucing15@mail.com')  ////////////////------------
    cy.wait(2000)
    cy.get('.btn-group > .btn > .fas').click()
    cy.get('[href="facilitator/detail/229"]').click()                       ////////////////------------

    cy.get('#user_email').should('have.text','kucing15@mail.com')          ////////////////------------
    cy.get('#user_is_active > .badge').should('exist')
    cy.get('#user_province_name').should('have.text','ACEH').should('exist')
    cy.get('#user_city_name').should('have.text','KAB. ACEH SELATAN').should('exist')
    cy.get('#user_subdistrict_name').should('have.text','Bakongan').should('exist')
    cy.get('#user_address').should('exist')
    cy.get('.alert').should('exist').should('have.text','Alamat penugasan diatur sama dengan alamat domisili fasilitator')
    cy.get('#user_province_name').should('have.text','ACEH').should('exist')
    cy.get('#user_city_name').should('have.text','KAB. ACEH SELATAN').should('exist')
    cy.get('#user_subdistrict_name').should('have.text','Bakongan').should('exist')
    cy.get('.btn-outline-primary').click()

    cy.get('#user_fullname').type(' UBAH KUCING 1')
    cy.get('#user_is_active').select('Aktif')
    cy.get('#user_province_id').select('RIAU')
    cy.get('#user_city_id').select('KAB. KAMPAR')
    cy.get('#user_subdistrict_id').select('Tambang')
    cy.get('#user_address').type('   HEHEHE')
    cy.get('#user_area_province_id').should('contain','RIAU').should('exist')
    cy.get('#user_area_city_id').should('contain','KAB. KAMPAR').should('exist')
    cy.get('#user_area_subdistrict_id').should('contain','Tambang').should('exist')
    cy.get('#edit').click()
    cy.get('#modal-title').should('have.text','Success')
    cy.get('#modal-body').should('have.text','Perubahan fasilitator berhasil diproses')
    cy.wait(2000)
    cy.get('#generalModal > .modal-dialog > .modal-content > .modal-footer > .btn').click()
    })
})  