describe('TEST 6', function() {
    it('UBAH', function() {
    cy.visit('https://admin.pkh.dojobox.id/')
    cy.get('#input-email').type('e@dojobox.id')
    cy.get('#input-password').type('admin')
    cy.get('#btn-login').click()
    cy.get('.mr-2 > b').should('have.text','Super Admin')
    
    cy.get(':nth-child(2) > .dt-center > .btn-group > .btn > .fas').click()
    cy.get('[href="facilitator/edit/6"]').contains('Ubah').click()    
    
    cy.get('#user_fullname').type(' UBAH KUCING 1')
    cy.get('#user_is_active').select('Aktif')
    cy.get('#user_province_id').select('RIAU')
    cy.get('#user_city_id').select('KAB. KAMPAR')
    cy.get('#user_subdistrict_id').select('Tambang')
    cy.get('#user_address').type('   HEHEHE ADDRESS BARU')
    cy.get('.custom-control').click()
    cy.get('#user_area_province_id').should('contain','RIAU').should('exist')
    cy.get('#user_area_city_id').should('contain','KAB. KAMPAR').should('exist')
    cy.get('#user_area_subdistrict_id').should('contain','Tambang').should('exist')
    cy.get('#edit').click()
    cy.get('#modal-title').should('have.text','Success')
    cy.get('#modal-body').should('have.text','Perubahan fasilitator berhasil diproses')
    cy.wait(1000)
    cy.get('#generalModal > .modal-dialog > .modal-content > .modal-footer > .btn').click()
    cy.get('#accordionSidebar > :nth-child(1) > .nav-link').click()
    cy.get('.mr-2 > b').should('have.text','Super Admin')
    })
})  
